### ISSUE TITLE
[Swift] Crash if deviceName less then 12 symbols

### ISSUE THREAD

**Issue by ILYA2606** [scooterhacking/NinebotCrypto#2] opened 2020-08-27 14:30 UTC
Crash if deviceName less then 12 symbols.  **GoKart**, for example.  
**NBScooter0915** is works, but user can change bluetooth name with official app.  

Example with livedata command:  
<img width="1882" alt="image" src="https://user-images.githubusercontent.com/283493/91455508-d54dd480-e88a-11ea-97f8-5b6ac31550c3.png">
<img width="1882" alt="image" src="https://user-images.githubusercontent.com/283493/91455541-ded73c80-e88a-11ea-8290-df80c17a0357.png">

**Comment by nopbxlr** [comment] 2020-08-27 22:02
Hello,
Since I couldn't reproduce the issue on the original C# version of the lib (implemented in Ninebot IAP), I can safely assume that this issue is Swift specific.

I have no idea about Swift though, so hopefully the contributor who ported it will pitch in and help! @robbiet480

**Comment by robbiet480** [comment] 2020-08-27 22:09
Thanks for the ping @lothean-dev 

Sadly @ILYA2606 you are gonna be on your own for this one because I'm not actively using this code anymore (I stopped working on the project entirely). @lothean-dev is right that if its not happening in the C# code it must be a translation issue with my Swift code. Perhaps you can try playing with the at argument of the insert and see if you can insert at the end instead?

**Comment by ILYA2606** [comment] 2020-08-27 22:27
@robbiet480 @lothean-dev Thanks for response! I fix it by adding zero bytes in deviceName.  
While you are here, tell me if I understand correctly:  
1) deviceName is bluetooth name? **NBScooter0915**, for example
2) Ninebot ES live data command for encryption is **5A A5 01 3E 20 01 B0 20 CF FE**? Don't need to increase the package size?

**Comment by robbiet480** [comment] 2020-08-27 22:28
1. I believe that is correct, yes.
2. You would want to ask @lothean-dev or @majsi

**Comment by robbiet480** [comment] 2020-11-08 03:42
@ILYA2606 If you’ve fixed the issues, it would be really appreciated if you contributed the fixes back to this repo. Thanks!

**Comment by LexNastin** [comment] 2024-01-05 11:31
Shouldn't be waking a 3+ year old thread, BUT this issue among others in the Swift implementation are closed by #12 :D

**Closed as completed** 2024-09-26 15:09 UTC
